apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployement
  labels:
    app: todo
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      component: redis
  template:
    metadata:
      labels:
        app: todo
        component: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 10m
        args:
        - redis-server 
        - --requirepass ccp2 
        - --appendonly yes
